UPDATE productos SET pro_imagen = '1agua mineral.jpg' WHERE pro_id = 1;
UPDATE productos SET pro_imagen = '2agua mineral 1.5l.jpg' WHERE pro_id = 2;
UPDATE productos SET pro_imagen = '10cola sin azucar.jpg' WHERE pro_id = 3;
UPDATE productos SET pro_imagen = '12fanta.jpg' WHERE pro_id = 4;
UPDATE productos SET pro_imagen = '1agua mineral.jpg' WHERE pro_id = 5;
UPDATE productos SET pro_imagen = '13 galleta amor.jpg' WHERE pro_id = 6;
UPDATE productos SET pro_imagen = '7chocolate galak.jpg' WHERE pro_id = 7;
UPDATE productos SET pro_imagen = '14galleta ritz.jpg' WHERE pro_id = 8;
UPDATE productos SET pro_imagen = '8chocolate mini.jpg' WHERE pro_id = 9;
UPDATE productos SET pro_imagen = '20yogut.jpg' WHERE pro_id = 10;
UPDATE productos SET pro_imagen = '16leche tony.jpg' WHERE pro_id = 11;
UPDATE productos SET pro_imagen = '17manjar.jpg' WHERE pro_id = 12;
UPDATE productos SET pro_imagen = '18queso crema.jpg' WHERE pro_id = 13;
UPDATE productos SET pro_imagen = '14galleta ritz.jpg' WHERE pro_id = 14;
UPDATE productos SET pro_imagen = '19sal yodo.jpg' WHERE pro_id = 15;
UPDATE productos SET pro_imagen = '5cereal nestle.jpg' WHERE pro_id = 16;
UPDATE productos SET pro_imagen = '4atun.jpg' WHERE pro_id = 17;
UPDATE productos SET pro_imagen = '15javonliquido.jpg' WHERE pro_id = 18;
UPDATE productos SET pro_imagen = '6champu palmolive.jpg' WHERE pro_id = 19;
UPDATE productos SET pro_imagen = '11desodorante.jpg' WHERE pro_id = 20;
